package assignment;

import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.time.Duration;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class SauceDemoTest {

    // ============================================================
    // CONFIGURATION
    // ============================================================

    private static final String SAUCE_DEMO_URL =
            "https://www.saucedemo.com/";

    private static final String USERNAME =
            "standard_user";

    private static final String PASSWORD =
            "secret_sauce";

    private static final Duration TIMEOUT =
            Duration.ofSeconds(10);

    /*
     * These delays are intentionally longer so that the
     * automation can be visually followed in the browser.
     */
    private static final int ACTION_DELAY = 2500;
    private static final int VERIFICATION_DELAY = 3500;

    // ============================================================
    // HELPER - PAUSE
    // ============================================================

    private void pause(int milliseconds) {

        try {

            Thread.sleep(milliseconds);

        } catch (InterruptedException e) {

            Thread.currentThread().interrupt();

            throw new RuntimeException(
                    "Test interrupted while waiting.",
                    e
            );
        }
    }

    // ============================================================
    // HELPER - SCROLL TO ELEMENT
    // ============================================================

    private void scrollToElement(
            WebDriver driver,
            WebElement element) {

        ((org.openqa.selenium.JavascriptExecutor) driver)
                .executeScript(
                        "arguments[0].scrollIntoView({behavior:'smooth', block:'center'});",
                        element
                );

        pause(1000);
    }

    // ============================================================
    // HELPER - CLICK ELEMENT VISIBLY
    // ============================================================

    private void clickElement(
            WebDriver driver,
            WebElement element) {

        scrollToElement(driver, element);

        element.click();

        pause(ACTION_DELAY);
    }

    // ============================================================
    // HELPER - HANDLE CHROME PASSWORD POPUP
    // ============================================================

    private void handlePasswordPopup(WebDriver driver) {

        /*
         * The "Change your password" popup is generated by Chrome,
         * not by SauceDemo.
         *
         * Selenium normally cannot interact with Chrome's own
         * browser UI because it is outside the webpage DOM.
         *
         * Therefore, the safest approach is to disable Chrome's
         * password manager notifications through ChromeOptions.
         *
         * This method is kept here so the test clearly documents
         * that the browser popup is intentionally handled.
         */

        System.out.println(
                "Checking for browser password notification..."
        );

        pause(1500);

        System.out.println(
                "Browser notification handling completed."
        );
    }

    // ============================================================
    // MAIN TEST
    // ============================================================

    @Test
    public void completePurchase() {

        ChromeOptions options = new ChromeOptions();

        // ========================================================
        // DISABLE CHROME PASSWORD MANAGER NOTIFICATIONS
        // ========================================================

        options.addArguments("--disable-notifications");

        options.setExperimentalOption(
                "prefs",
                Map.of(
                        "credentials_enable_service", false,
                        "profile.password_manager_enabled", false,
                        "profile.password_manager_leak_detection", false
                )
        );

        WebDriver driver =
                new ChromeDriver(options);

        WebDriverWait wait =
                new WebDriverWait(driver, TIMEOUT);

        try {

            System.out.println();
            System.out.println("==============================================");
            System.out.println("        SAUCE DEMO AUTOMATION TEST");
            System.out.println("==============================================");

            // ====================================================
            // 1. LOGIN
            // ====================================================

            System.out.println();
            System.out.println("[1/5] LOGIN");
            System.out.println("----------------------------------------------");

            System.out.println(
                    "Opening SauceDemo website..."
            );

            driver.get(SAUCE_DEMO_URL);

            wait.until(
                    ExpectedConditions.visibilityOfElementLocated(
                            By.id("user-name")
                    )
            );

            pause(VERIFICATION_DELAY);

            handlePasswordPopup(driver);

            // ----------------------------------------------------
            // Username
            // ----------------------------------------------------

            System.out.println(
                    "Entering username..."
            );

            WebElement usernameField =
                    driver.findElement(
                            By.id("user-name")
                    );

            usernameField.sendKeys(USERNAME);

            pause(ACTION_DELAY);

            // ----------------------------------------------------
            // Password
            // ----------------------------------------------------

            System.out.println(
                    "Entering password..."
            );

            WebElement passwordField =
                    driver.findElement(
                            By.id("password")
                    );

            passwordField.sendKeys(PASSWORD);

            pause(ACTION_DELAY);

            // ----------------------------------------------------
            // Login
            // ----------------------------------------------------

            System.out.println(
                    "Clicking Login button..."
            );

            WebElement loginButton =
                    driver.findElement(
                            By.id("login-button")
                    );

            clickElement(driver, loginButton);

            wait.until(
                    ExpectedConditions.visibilityOfElementLocated(
                            By.className("title")
                    )
            );

            pause(VERIFICATION_DELAY);

            // ----------------------------------------------------
            // Verify Login
            // ----------------------------------------------------

            String pageTitle =
                    driver.findElement(
                            By.className("title")
                    ).getText();

            assertEquals(
                    "Products",
                    pageTitle,
                    "Login failed - Products page was not displayed."
            );

            System.out.println(
                    "PASS - Login successful."
            );

            System.out.println(
                    "PASS - Products page displayed."
            );

            pause(VERIFICATION_DELAY);

            // ====================================================
            // 2. ADD THREE PRODUCTS
            // ====================================================

            System.out.println();
            System.out.println("[2/5] ADD 3 PRODUCTS");
            System.out.println("----------------------------------------------");

            // ----------------------------------------------------
            // Product 1 - Backpack
            // ----------------------------------------------------

            System.out.println();
            System.out.println(
                    "Product 1: Sauce Labs Backpack"
            );

            WebElement backpackButton =
                    wait.until(
                            ExpectedConditions.elementToBeClickable(
                                    By.id(
                                            "add-to-cart-sauce-labs-backpack"
                                    )
                            )
                    );

            System.out.println(
                    "Clicking 'Add to cart'..."
            );

            clickElement(
                    driver,
                    backpackButton
            );

            // Verify button changed to Remove

            WebElement removeBackpack =
                    wait.until(
                            ExpectedConditions.visibilityOfElementLocated(
                                    By.id(
                                            "remove-sauce-labs-backpack"
                                    )
                            )
                    );

            assertTrue(
                    removeBackpack.isDisplayed(),
                    "Backpack was not added to the cart."
            );

            System.out.println(
                    "PASS - Backpack added to cart."
            );

            pause(VERIFICATION_DELAY);

            // ----------------------------------------------------
            // Product 2 - Bike Light
            // ----------------------------------------------------

            System.out.println();
            System.out.println(
                    "Product 2: Sauce Labs Bike Light"
            );

            WebElement bikeLightButton =
                    wait.until(
                            ExpectedConditions.elementToBeClickable(
                                    By.id(
                                            "add-to-cart-sauce-labs-bike-light"
                                    )
                            )
                    );

            System.out.println(
                    "Clicking 'Add to cart'..."
            );

            clickElement(
                    driver,
                    bikeLightButton
            );

            WebElement removeBikeLight =
                    wait.until(
                            ExpectedConditions.visibilityOfElementLocated(
                                    By.id(
                                            "remove-sauce-labs-bike-light"
                                    )
                            )
                    );

            assertTrue(
                    removeBikeLight.isDisplayed(),
                    "Bike Light was not added to the cart."
            );

            System.out.println(
                    "PASS - Bike Light added to cart."
            );

            pause(VERIFICATION_DELAY);

            // ----------------------------------------------------
            // Product 3 - Bolt T-Shirt
            // ----------------------------------------------------

            System.out.println();
            System.out.println(
                    "Product 3: Sauce Labs Bolt T-Shirt"
            );

            WebElement boltShirtButton =
                    wait.until(
                            ExpectedConditions.elementToBeClickable(
                                    By.id(
                                            "add-to-cart-sauce-labs-bolt-t-shirt"
                                    )
                            )
                    );

            System.out.println(
                    "Clicking 'Add to cart'..."
            );

            clickElement(
                    driver,
                    boltShirtButton
            );

            WebElement removeBoltShirt =
                    wait.until(
                            ExpectedConditions.visibilityOfElementLocated(
                                    By.id(
                                            "remove-sauce-labs-bolt-t-shirt"
                                    )
                            )
                    );

            assertTrue(
                    removeBoltShirt.isDisplayed(),
                    "Bolt T-Shirt was not added to the cart."
            );

            System.out.println(
                    "PASS - Bolt T-Shirt added to cart."
            );

            pause(VERIFICATION_DELAY);

            // ====================================================
            // VERIFY CART COUNT
            // ====================================================

            WebElement cartBadge =
                    wait.until(
                            ExpectedConditions.visibilityOfElementLocated(
                                    By.className(
                                            "shopping_cart_badge"
                                    )
                            )
                    );

            String cartCount =
                    cartBadge.getText();

            assertEquals(
                    "3",
                    cartCount,
                    "Expected 3 products in the cart."
            );

            System.out.println();
            System.out.println(
                    "PASS - Cart badge shows 3 products."
            );

            pause(VERIFICATION_DELAY);

            // ====================================================
            // OPEN CART
            // ====================================================

            System.out.println();
            System.out.println(
                    "Opening shopping cart..."
            );

            WebElement cartLink =
                    driver.findElement(
                            By.className(
                                    "shopping_cart_link"
                            )
                    );

            clickElement(
                    driver,
                    cartLink
            );

            wait.until(
                    ExpectedConditions.visibilityOfElementLocated(
                            By.className("cart_list")
                    )
            );

            pause(VERIFICATION_DELAY);

            // ====================================================
            // VERIFY THREE PRODUCTS IN CART
            // ====================================================

            String cartItems =
                    driver.findElement(
                            By.className("cart_list")
                    ).getText();

            System.out.println();
            System.out.println(
                    "=============================================="
            );

            System.out.println(
                    "PRODUCTS CURRENTLY IN CART:"
            );

            System.out.println(
                    cartItems
            );

            System.out.println(
                    "=============================================="
            );

            assertTrue(
                    cartItems.contains(
                            "Sauce Labs Backpack"
                    ),
                    "Backpack is missing from cart."
            );

            assertTrue(
                    cartItems.contains(
                            "Sauce Labs Bike Light"
                    ),
                    "Bike Light is missing from cart."
            );

            assertTrue(
                    cartItems.contains(
                            "Sauce Labs Bolt T-Shirt"
                    ),
                    "Bolt T-Shirt is missing from cart."
            );

            System.out.println(
                    "PASS - All 3 products verified in cart."
            );

            pause(VERIFICATION_DELAY);

            // ====================================================
            // 3. REMOVE ONE PRODUCT
            // ====================================================

            System.out.println();
            System.out.println("[3/5] REMOVE 1 PRODUCT");
            System.out.println("----------------------------------------------");

            System.out.println(
                    "Removing: Sauce Labs Backpack"
            );

            WebElement removeBackpackButton =
                    wait.until(
                            ExpectedConditions.elementToBeClickable(
                                    By.id(
                                            "remove-sauce-labs-backpack"
                                    )
                            )
                    );

            clickElement(
                    driver,
                    removeBackpackButton
            );

            pause(VERIFICATION_DELAY);

            // ----------------------------------------------------
            // Verify cart count
            // ----------------------------------------------------

            cartBadge =
                    wait.until(
                            ExpectedConditions.visibilityOfElementLocated(
                                    By.className(
                                            "shopping_cart_badge"
                                    )
                            )
                    );

            cartCount =
                    cartBadge.getText();

            assertEquals(
                    "2",
                    cartCount,
                    "Expected 2 products after removing one."
            );

            System.out.println(
                    "PASS - Cart now contains 2 products."
            );

            // ----------------------------------------------------
            // Verify remaining products
            // ----------------------------------------------------

            cartItems =
                    driver.findElement(
                            By.className("cart_list")
                    ).getText();

            System.out.println();
            System.out.println(
                    "REMAINING PRODUCTS:"
            );

            System.out.println(
                    cartItems
            );

            assertTrue(
                    !cartItems.contains(
                            "Sauce Labs Backpack"
                    ),
                    "Backpack was not removed."
            );

            assertTrue(
                    cartItems.contains(
                            "Sauce Labs Bike Light"
                    ),
                    "Bike Light is missing."
            );

            assertTrue(
                    cartItems.contains(
                            "Sauce Labs Bolt T-Shirt"
                    ),
                    "Bolt T-Shirt is missing."
            );

            System.out.println(
                    "PASS - Backpack successfully removed."
            );

            System.out.println(
                    "PASS - Correct 2 products remain."
            );

            pause(VERIFICATION_DELAY);

            // ====================================================
            // 4. CHECKOUT
            // ====================================================

            System.out.println();
            System.out.println("[4/5] CHECKOUT");
            System.out.println("----------------------------------------------");

            System.out.println(
                    "Clicking Checkout..."
            );

            WebElement checkoutButton =
                    wait.until(
                            ExpectedConditions.elementToBeClickable(
                                    By.id("checkout")
                            )
                    );

            clickElement(
                    driver,
                    checkoutButton
            );

            wait.until(
                    ExpectedConditions.visibilityOfElementLocated(
                            By.id("first-name")
                    )
            );

            pause(VERIFICATION_DELAY);

            // ----------------------------------------------------
            // First Name
            // ----------------------------------------------------

            System.out.println(
                    "Entering first name: Boitumelo"
            );

            WebElement firstName =
                    driver.findElement(
                            By.id("first-name")
                    );

            firstName.sendKeys("Boitumelo");

            pause(ACTION_DELAY);

            // ----------------------------------------------------
            // Last Name
            // ----------------------------------------------------

            System.out.println(
                    "Entering last name: Khauoe"
            );

            WebElement lastName =
                    driver.findElement(
                            By.id("last-name")
                    );

            lastName.sendKeys("Khauoe");

            pause(ACTION_DELAY);

            // ----------------------------------------------------
            // Postal Code
            // ----------------------------------------------------

            System.out.println(
                    "Entering postal code: 1448"
            );

            WebElement postalCode =
                    driver.findElement(
                            By.id("postal-code")
                    );

            postalCode.sendKeys("1448");

            pause(VERIFICATION_DELAY);

            // ----------------------------------------------------
            // Continue
            // ----------------------------------------------------

            System.out.println(
                    "Clicking Continue..."
            );

            WebElement continueButton =
                    driver.findElement(
                            By.id("continue")
                    );

            clickElement(
                    driver,
                    continueButton
            );

            wait.until(
                    ExpectedConditions.visibilityOfElementLocated(
                            By.id("finish")
                    )
            );

            pause(VERIFICATION_DELAY);

            // ====================================================
            // VERIFY CHECKOUT PRODUCTS
            // ====================================================

            String checkoutItems =
                    driver.findElement(
                            By.className("cart_list")
                    ).getText();

            System.out.println();
            System.out.println(
                    "=============================================="
            );

            System.out.println(
                    "PRODUCTS AT CHECKOUT:"
            );

            System.out.println(
                    checkoutItems
            );

            System.out.println(
                    "=============================================="
            );

            assertTrue(
                    checkoutItems.contains(
                            "Sauce Labs Bike Light"
                    ),
                    "Bike Light is missing from checkout."
            );

            assertTrue(
                    checkoutItems.contains(
                            "Sauce Labs Bolt T-Shirt"
                    ),
                    "Bolt T-Shirt is missing from checkout."
            );

            assertTrue(
                    !checkoutItems.contains(
                            "Sauce Labs Backpack"
                    ),
                    "Backpack should not be at checkout."
            );

            System.out.println(
                    "PASS - Checkout contains the correct products."
            );

            pause(VERIFICATION_DELAY);

            // ====================================================
            // FINISH ORDER
            // ====================================================

            System.out.println();
            System.out.println(
                    "Clicking Finish to place the order..."
            );

            WebElement finishButton =
                    wait.until(
                            ExpectedConditions.elementToBeClickable(
                                    By.id("finish")
                            )
                    );

            clickElement(
                    driver,
                    finishButton
            );

            // ====================================================
            // 5. VERIFY ORDER COMPLETION
            // ====================================================

            System.out.println();
            System.out.println(
                    "[5/5] VERIFY ORDER COMPLETION"
            );

            System.out.println(
                    "----------------------------------------------"
            );

            wait.until(
                    ExpectedConditions.visibilityOfElementLocated(
                            By.className(
                                    "complete-header"
                            )
                    )
            );

            pause(VERIFICATION_DELAY);

            String confirmation =
                    driver.findElement(
                            By.className(
                                    "complete-header"
                            )
                    ).getText();

            System.out.println();
            System.out.println(
                    "Order confirmation message:"
            );

            System.out.println(
                    confirmation
            );

            assertEquals(
                    "Thank you for your order!",
                    confirmation,
                    "Order completion message was not displayed."
            );

            System.out.println();
            System.out.println(
                    "PASS - Order completed successfully."
            );

            pause(VERIFICATION_DELAY);

            // ====================================================
            // FINAL RESULT
            // ====================================================

            System.out.println();
            System.out.println(
                    "=============================================="
            );

            System.out.println(
                    "          SAUCE DEMO TEST PASSED"
            );

            System.out.println(
                    "=============================================="
            );

            System.out.println(
                    "✓ Login"
            );

            System.out.println(
                    "✓ Products page verified"
            );

            System.out.println(
                    "✓ Sauce Labs Backpack added"
            );

            System.out.println(
                    "✓ Sauce Labs Bike Light added"
            );

            System.out.println(
                    "✓ Sauce Labs Bolt T-Shirt added"
            );

            System.out.println(
                    "✓ 3 products verified in cart"
            );

            System.out.println(
                    "✓ 1 product removed"
            );

            System.out.println(
                    "✓ 2 remaining products verified"
            );

            System.out.println(
                    "✓ Checkout completed"
            );

            System.out.println(
                    "✓ Checkout products verified"
            );

            System.out.println(
                    "✓ Order completion verified"
            );

            System.out.println(
                    "=============================================="
            );

            pause(VERIFICATION_DELAY);

        } catch (Exception e) {

            // ====================================================
            // FAILURE
            // ====================================================

            System.out.println();
            System.out.println(
                    "=============================================="
            );

            System.out.println(
                    "          SAUCE DEMO TEST FAILED"
            );

            System.out.println(
                    "=============================================="
            );

            System.out.println(
                    "Reason: " + e.getMessage()
            );

            System.out.println(
                    "=============================================="
            );

            throw e;

        } finally {

            // ====================================================
            // CLOSE BROWSER
            // ====================================================

            System.out.println();
            System.out.println(
                    "Browser will close shortly..."
            );

            pause(VERIFICATION_DELAY);

            driver.quit();

            System.out.println(
                    "Browser closed."
            );
        }
    }
}